VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.network 'private_network', type: 'dhcp'
  config.vm.provision 'ansible' do |ansible|
    ansible.sudo = true
    ansible.playbook = '../vagrant.yml'
    #ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
  end
end
